[tox]
minversion = 1.8
envlist = py{37,39}-ansible{210,30}
skipsdist = true

[testenv]
passenv = *
deps =
    -r tox-requirements.txt
    ansible210: ansible<3.0
    ansible30: ansible<3.1
commands_pre =
        /bin/bash -lc 'if [ -f /etc/containers/containers.conf ]; then sed -i "s/^cgroups=.*/cgroups=\"enabled\"/" /etc/containers/containers.conf; sed -i "s/^runtime=.*/runtime=\"runc\"/" /etc/containers/containers.conf; fi'
commands =
    {posargs:molecule test -s compatibility}

[testenv:py37-ansible210]
basepython = python3.7

[testenv:py37-ansible30]
basepython = python3.7

[testenv:py39-ansible210]
basepython = python3.9

[testenv:py39-ansible30]
basepython = python3.9
